# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField()),
                ('query_type', models.CharField(default='Exam', max_length=240)),
                ('email', models.CharField(db_index=True, max_length=48)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=12)),
                ('status', models.BooleanField(default=False)),
                ('token_id', models.CharField(blank=True, default='', max_length=24, null=True)),
            ],
            options={
                'verbose_name_plural': 'Queries',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('slot_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='querytoken',
            name='slot',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='query_management.TimeSlot'),
        ),
    ]
