# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('student', models.IntegerField(primary_key=True, serialize=False)),
                ('query_type', models.CharField(default='Exam', max_length=240)),
                ('email', models.CharField(db_index=True, max_length=48)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Queries',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('slot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('finish', models.TimeField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField()),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='query_management.TimeSlot')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='query_management.Query')),
            ],
        ),
    ]
