# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='slot_id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
