# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_management', '0002_auto_20170313_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='slot_id',
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
    ]
