# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-05 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query_management', '0003_auto_20170305_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_management.TimeSlot'),
        ),
    ]
