# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('query_management', '0003_auto_20170313_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querytoken',
            name='slot',
        ),
        migrations.AddField(
            model_name='querytoken',
            name='department',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='querytoken',
            name='description',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='querytoken',
            name='year',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='querytoken',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='querytoken',
            name='query_type',
            field=models.CharField(choices=[('Result', 'Result Discrepency'), ('Credit', 'Credit Discrepency'), ('PDC Issue', 'Issue of PDC'), ('Other Certificate', 'Issue of some other certificate')], db_index=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='querytoken',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
