# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-05 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_management', '0005_auto_20170305_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_id',
            field=models.CharField(max_length=24),
        ),
    ]
