# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 19:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_management', '0006_auto_20170317_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querytoken',
            name='date',
            field=models.DateField(default=datetime.date(2017, 3, 16)),
        ),
        migrations.AlterField(
            model_name='querytoken',
            name='time',
            field=models.TimeField(default=datetime.time(19, 38, 6, 394688)),
        ),
    ]
