# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_management', '0007_auto_20170317_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querytoken',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='querytoken',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
