# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 22:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_management', '0012_auto_20170320_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querytoken',
            name='query_type',
            field=models.CharField(choices=[('result', 'Result Discrepency'), ('credit', 'Credit Discrepency'), ('pdc_issue', 'Issue of PDC'), ('other_certificate', 'Issue of some other certificate')], max_length=240),
        ),
        migrations.AlterField(
            model_name='querytoken',
            name='time',
            field=models.TimeField(default=datetime.time(3, 43, 55, 829833)),
        ),
    ]
