# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 03:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_management', '0014_auto_20170320_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querytoken',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='querytoken',
            name='time',
            field=models.TimeField(default=datetime.time(8, 58, 30, 76634)),
        ),
    ]
