# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 03:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_management', '0016_auto_20170325_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querytoken',
            name='date',
            field=models.DateField(default=datetime.date(2017, 3, 25)),
        ),
        migrations.AlterField(
            model_name='querytoken',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0, 13, 555388)),
        ),
    ]
