# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Datesheet',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=48)),
                ('department', models.CharField(max_length=12)),
                ('designation', models.CharField(choices=[('Assistant_Professor', 'Assistant Professor'), ('Professor', 'Professor'), ('Non-Teaching', 'Non-Teaching')], default='Assistant_Professor', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True)),
                ('room_type', models.CharField(choices=[('Audi', 'Auditorium'), ('Classroom', 'Classroom')], default='Classroom', max_length=20)),
                ('capacity', models.IntegerField(default=64)),
                ('block_number', models.IntegerField()),
                ('building_name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('system_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=48)),
                ('branch', models.CharField(max_length=48)),
                ('year', models.CharField(max_length=2)),
                ('semester', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(default=None, max_length=12, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(default=None, max_length=48)),
                ('department', models.CharField(default='CSE', max_length=12)),
                ('paper_code', models.CharField(default=None, max_length=12, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(default=None, to='seating_manager.Subject'),
        ),
        migrations.AddField(
            model_name='datesheet',
            name='subject_id',
            field=models.ManyToManyField(default=None, to='seating_manager.Subject'),
        ),
    ]
